version: "3.8"
services:
    postgres:
        image: postgres
        ports:
          - 5432:5432
        environment:
            POSTGRES_USER: super-burger-user
            POSTGRES_PASSWORD: super-burger-password
            POSTGRES_DB: super-burger
